In [2]:
!pip install ipynb

Requirement already satisfied: ipynb in ./rapids-cuml/lib/python3.10/site-packages (0.5.1)

In [3]:
import torch
import gc

In [4]:
from ipynb.fs.full.Normalization_to_import import *

Execution time: 0.5987615585327148 seconds

In [5]:
from ipynb.fs.full.Data_Generation_to_import import *

Execution time: 0.0407557487487793 seconds

In [6]:
from ipynb.fs.full.Machine_Learning_to_import import *

Execution time: 308.0362939834595 seconds
Metrics for not normalized data is ready. Run 'metrics.main()'!
Execution time: 304.3837490081787 seconds
Metrics for maxAbsScaler normalized data is ready. Run 'metrics_maxAbsScaler.main()'!
Execution time: 307.86973881721497 seconds
Metrics for MinMaxScaler normalized data is ready. Run 'metrics_MinMaxScaler.main()'!
Execution time: 306.2628514766693 seconds
Metrics for normalizer normalized data is ready. Run 'metrics_normalizer.main()'!
Execution time: 306.3142991065979 seconds
Metrics for robust_scaler normalized data is ready. Run 'metrics_robust_scaler.main()'!
Execution time: 308.65684628486633 seconds
Metrics for standard_scaler normalized data is ready. Run 'metrics_standard_scaler.main()'!
Execution time: 310.2523744106293 seconds
Metrics for binarizer normalized data is ready. Run 'metrics_binarizer.main()'!
Execution time: 308.00619316101074 seconds
Metrics for function_transformer normalized data is ready. Run 'metrics_function_transformer.main()'!
Execution time: 305.8683371543884 seconds
Metrics for KBinsDiscretizer normalized data is ready. Run 'metrics_KBinsDiscretizer.main()'!

In [7]:
torch.cuda.empty_cache()
gc.collect()

0

In [8]:
from ipynb.fs.full.Naive_Bayes_to_import import *

/home/xy/Desktop/ml/rapids-cuml/lib/python3.10/site-packages/cuml/naive_bayes/naive_bayes.py:1563: UserWarning: X dtype is not int32. X will be converted, which will increase memory consumption
  warnings.warn(
/home/xy/Desktop/ml/rapids-cuml/lib/python3.10/site-packages/cuml/naive_bayes/naive_bayes.py:1589: UserWarning: X dtype is not int32. X will be converted, which will increase memory consumption
  warnings.warn(

Execution time: 0.2854886054992676 seconds
Metrics for not normalized data is ready. Run 'metrics.main()'!
Execution time: 0.24848008155822754 seconds
Metrics for MaxAbsScaler normalized data is ready. Run 'metrics_MaxAbsScaler.main()'!
Execution time: 0.2477109432220459 seconds
Metrics for MinMaxScaler normalized data is ready. Run 'metrics_MinMaxScaler.main()'!
Execution time: 0.24589872360229492 seconds
Metrics for Normalizer normalized data is ready. Run 'metrics_Normalizer.main()'!
Execution time: 0.2490229606628418 seconds
Metrics for Binarizer normalized data is ready. Run 'metrics_Binarizer.main()'!
Execution time: 0.24744343757629395 seconds
Metrics for FunctionTransformer normalized data is ready. Run 'metrics_FunctionTransformer.main()'!
Execution time: 0.2439875602722168 seconds
Metrics for KBinsDiscretizer normalized data is ready. Run 'metrics_KBinsDiscretizer.main()'!

In [ ]:
torch.cuda.empty_cache()
gc.collect()

In [9]:
from ipynb.fs.full.Neighbours_to_import import *

Execution time: 6.542048454284668 seconds
Metrics for not normalized data is ready. Run 'metrics.main()'!
Execution time: 8.842800617218018 seconds
Metrics for MaxAbsScaler normalized data is ready. Run 'metrics_MaxAbsScaler.main()'!
Execution time: 9.641408920288086 seconds
Metrics for MinMaxScaler normalized data is ready. Run 'metrics_MinMaxScaler.main()'!
Execution time: 9.805320978164673 seconds
Metrics for Normalizer normalized data is ready. Run 'metrics_Normalizer.main()'!
Execution time: 9.880279779434204 seconds
Metrics for Binarizer normalized data is ready. Run 'metrics_Binarizer.main()'!
Execution time: 9.904685258865356 seconds
Metrics for FunctionTransformer normalized data is ready. Run 'metrics_FunctionTransformer.main()'!
Execution time: 9.94062852859497 seconds
Metrics for KBinsDiscretizer normalized data is ready. Run 'metrics_KBinsDiscretizer.main()'!

In [ ]:
torch.cuda.empty_cache()
gc.collect()

In [10]:
#ml.LogisticRegression()

In [11]:
#logr_predict_global_1

        HeartDiseaseorAttack
0                        1.0
1                        1.0
2                        1.0
3                        1.0
4                        1.0
...                      ...
999995                   1.0
999996                   1.0
999997                   1.0
999998                   1.0
999999                   1.0

[1000000 rows x 1 columns]

In [13]:
#nb.GaussianNB()

In [14]:
bnb_predict_global_1

        HeartDiseaseorAttack
0                          0
1                          0
2                          1
3                          0
4                          0
...                      ...
999995                     1
999996                     1
999997                     1
999998                     0
999999                     0

[1000000 rows x 1 columns]

In [15]:
gnb_predict_global_1['HeartDiseaseorAttack'].unique()

0    1
1    0
Name: HeartDiseaseorAttack, dtype: int64

In [16]:
knc_predict_global_1

        HeartDiseaseorAttack
0                        0.0
1                        0.0
2                        1.0
3                        0.0
4                        0.0
...                      ...
999995                   1.0
999996                   1.0
999997                   1.0
999998                   0.0
999999                   1.0

[1000000 rows x 1 columns]

In [17]:
knc_predict_global_1['HeartDiseaseorAttack'].unique()

0    0.0
1    1.0
Name: HeartDiseaseorAttack, dtype: float64