In [1]:
!pip install ipynb

Requirement already satisfied: ipynb in ./rapids-cuml/lib/python3.10/site-packages (0.5.1)

In [2]:
from ipynb.fs.full.Normalization_to_import import *

Execution time: 0.6571416854858398 seconds

In [3]:
maxAbsScaler_merged_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375,0.0
1,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125,0.0
2,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000,0.0
3,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750,0.0
4,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875,0.0
253676,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500,0.0
253677,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250,0.0
253678,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125,0.0
253679,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250,1.0

In [4]:
MinMaxScaler_merged_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375,0.0
1,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125,0.0
2,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000,0.0
3,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750,0.0
4,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875,0.0
253676,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500,0.0
253677,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250,0.0
253678,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125,0.0
253679,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250,1.0

In [5]:
normalizer_merged_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375,0.0
1,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125,0.0
2,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000,0.0
3,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750,0.0
4,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875,0.0
253676,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500,0.0
253677,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250,0.0
253678,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125,0.0
253679,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250,1.0

In [6]:
robust_scaler_merged_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375,0.0
1,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125,0.0
2,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000,0.0
3,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750,0.0
4,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875,0.0
253676,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500,0.0
253677,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250,0.0
253678,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125,0.0
253679,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250,1.0

In [7]:
standard_scaler_merged_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375,0.0
1,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125,0.0
2,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000,0.0
3,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750,0.0
4,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875,0.0
253676,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500,0.0
253677,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250,0.0
253678,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125,0.0
253679,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250,1.0

In [8]:
binarizer_merged_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375,0.0
1,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125,0.0
2,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000,0.0
3,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750,0.0
4,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875,0.0
253676,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500,0.0
253677,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250,0.0
253678,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125,0.0
253679,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250,1.0

In [9]:
function_transformer_merged_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375,0.0
1,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125,0.0
2,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000,0.0
3,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750,0.0
4,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875,0.0
253676,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500,0.0
253677,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250,0.0
253678,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125,0.0
253679,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250,1.0

In [10]:
KBinsDiscretizer_merged_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,HeartDiseaseorAttack
0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375,0.0
1,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125,0.0
2,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000,0.0
3,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750,0.0
4,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875,0.0
253676,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500,0.0
253677,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250,0.0
253678,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125,0.0
253679,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250,1.0

In [11]:
from ipynb.fs.full.Data_Generation_to_import import *

Execution time: 0.050997257232666016 seconds

In [12]:
generated_data_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.0,1.0,1.0,94.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,1.0,4.0,11.0,22.0,0.0,1.0,13.0,4.0,6.0
1,0.0,0.0,1.0,17.0,0.0,1.0,2.0,1.0,1.0,0.0,...,0.0,0.0,5.0,27.0,7.0,1.0,0.0,2.0,5.0,8.0
2,1.0,1.0,0.0,82.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.0,1.0,4.0,25.0,23.0,0.0,1.0,7.0,4.0,8.0
3,1.0,1.0,1.0,27.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,0.0,5.0,28.0,7.0,1.0,0.0,9.0,2.0,4.0
4,1.0,0.0,0.0,41.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,1.0,6.0,24.0,0.0,0.0,6.0,4.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999995,0.0,1.0,1.0,31.0,0.0,0.0,2.0,0.0,0.0,0.0,...,1.0,0.0,3.0,9.0,15.0,0.0,1.0,1.0,5.0,1.0
1999996,0.0,0.0,0.0,46.0,1.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,4.0,15.0,24.0,1.0,0.0,13.0,1.0,3.0
1999997,0.0,0.0,1.0,83.0,1.0,0.0,2.0,1.0,1.0,1.0,...,1.0,1.0,1.0,23.0,11.0,1.0,0.0,3.0,5.0,5.0
1999998,0.0,1.0,1.0,42.0,1.0,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,5.0,24.0,8.0,0.0,1.0,12.0,4.0,8.0
1999999,0.0,1.0,0.0,44.0,0.0,1.0,2.0,0.0,0.0,0.0,...,0.0,0.0,4.0,21.0,22.0,1.0,1.0,1.0,4.0,5.0

In [13]:
from ipynb.fs.full.Machine_Learning_to_import import *

Execution time: 312.1747853755951 seconds
Metrics for not normalized data is ready. Run 'metrics.main()'!
Execution time: 313.18742752075195 seconds
Metrics for maxAbsScaler normalized data is ready. Run 'metrics_maxAbsScaler.main()'!
Execution time: 316.5351366996765 seconds
Metrics for MinMaxScaler normalized data is ready. Run 'metrics_MinMaxScaler.main()'!
Execution time: 312.43477153778076 seconds
Metrics for normalizer normalized data is ready. Run 'metrics_normalizer.main()'!
Execution time: 312.2060742378235 seconds
Metrics for robust_scaler normalized data is ready. Run 'metrics_robust_scaler.main()'!
Execution time: 311.84952306747437 seconds
Metrics for standard_scaler normalized data is ready. Run 'metrics_standard_scaler.main()'!
Execution time: 312.67887353897095 seconds
Metrics for binarizer normalized data is ready. Run 'metrics_binarizer.main()'!
Execution time: 312.4586319923401 seconds
Metrics for function_transformer normalized data is ready. Run 'metrics_function_transformer.main()'!
Execution time: 312.8769519329071 seconds
Metrics for KBinsDiscretizer normalized data is ready. Run 'metrics_KBinsDiscretizer.main()'!

In [14]:
metrics.main()

 Linear Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Linear Regression Intercept:
-0.14270589939952721


Mean squared error:
0.07244965790139588


Median Absolute Error:
0.0848178224741479


R2 Score:
0.14910311630140172


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Logistic Regression Coef:
         0         1         2         3         4         5         6   \
0  0.528893  0.608392  0.469695  0.060202  0.365066  0.979838  0.308809

        7         8         9   ...        11        12        13        14  \
0  0.04745  0.004294  0.045237  ... -0.039733  0.237768  2.459549  0.071788

         15        16        17        18        19        20
0  0.032139  0.293429  0.755856  3.277001  0.081932 -0.352729

[1 rows x 21 columns]


Logistic Regression Intercept:
0   -7.79723
dtype: float64


Mean squared error:
0.09165089877010407


Mean Squared Log Error:
0.044033950542408475


Median Absolute Error:
0.0


R2 Score:
-0.07640900468840894


Accuracy Score:
0.908349101229896


Kl Divergence:
inf


ROC AUC Score:
0.5601204037666321


Unique Values:
0    0.0
1    1.0
dtype: float64
Ridge Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Ridge Regression Intercept:
-0.14270589957679403


Mean squared error:
0.07244965790146864


Median Absolute Error:
0.08481782255129641


R2 Score:
0.14910311630054696


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Lasso Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


Lasso Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Mean Squared Log Error:
0.04152912296598731


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801277


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
ElasticNet Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


ElasticNet Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801278


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
Mini Batch SGD Classifier Coef:
0     3.249931
1     3.000867
2     1.006832
3    -0.060408
4     1.872501
5     3.528696
6     2.412563
7    -0.450228
8     0.218120
9    -0.166656
10   -0.742817
11    0.274712
12    0.548909
13    4.640031
14    0.580557
15    2.421096
16    2.978621
17    2.998615
18    7.549296
19   -0.986487
20   -2.382955
dtype: float64


Mini Batch SGD Classifier Intercept:
-11.36907251546996


Mean squared error:
0.3952223273415326


Median Absolute Error:
0.0


R2 Score:
-3.6417534111853715


Accuracy Score:
0.6047776726584674


Kl Divergence:
inf


ROC AUC Score:
0.7411006689071655


Unique Values:
0    0.0
1    1.0
dtype: float64

In [15]:
metrics_maxAbsScaler.main()

 Linear Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Linear Regression Intercept:
-0.14270589939952721


Mean squared error:
0.07244965790139588


Median Absolute Error:
0.0848178224741479


R2 Score:
0.14910311630140172


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Logistic Regression Coef:
         0         1         2         3         4         5         6   \
0  0.528893  0.608392  0.469695  0.060202  0.365066  0.979838  0.308809

        7         8         9   ...        11        12        13        14  \
0  0.04745  0.004294  0.045237  ... -0.039733  0.237768  2.459549  0.071788

         15        16        17        18        19        20
0  0.032139  0.293429  0.755856  3.277001  0.081932 -0.352729

[1 rows x 21 columns]


Logistic Regression Intercept:
0   -7.79723
dtype: float64


Mean squared error:
0.09165089877010407


Mean Squared Log Error:
0.044033950542408475


Median Absolute Error:
0.0


R2 Score:
-0.07640900468840894


Accuracy Score:
0.908349101229896


Kl Divergence:
inf


ROC AUC Score:
0.5601204037666321


Unique Values:
0    0.0
1    1.0
dtype: float64
Ridge Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Ridge Regression Intercept:
-0.14270589957679403


Mean squared error:
0.07244965790146864


Median Absolute Error:
0.08481782255129641


R2 Score:
0.14910311630054696


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Lasso Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


Lasso Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Mean Squared Log Error:
0.04152912296598731


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801277


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
ElasticNet Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


ElasticNet Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801278


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
Mini Batch SGD Classifier Coef:
0     3.249931
1     3.000867
2     1.006832
3    -0.060408
4     1.872501
5     3.528696
6     2.412563
7    -0.450228
8     0.218120
9    -0.166656
10   -0.742817
11    0.274712
12    0.548909
13    4.640031
14    0.580557
15    2.421096
16    2.978621
17    2.998615
18    7.549296
19   -0.986487
20   -2.382955
dtype: float64


Mini Batch SGD Classifier Intercept:
-11.36907251546996


Mean squared error:
0.3952223273415326


Median Absolute Error:
0.0


R2 Score:
-3.6417534111853715


Accuracy Score:
0.6047776726584674


Kl Divergence:
inf


ROC AUC Score:
0.7411006689071655


Unique Values:
0    0.0
1    1.0
dtype: float64

In [16]:
metrics_MinMaxScaler.main()

 Linear Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Linear Regression Intercept:
-0.14270589939952721


Mean squared error:
0.07244965790139588


Median Absolute Error:
0.0848178224741479


R2 Score:
0.14910311630140172


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Logistic Regression Coef:
         0         1         2         3         4         5         6   \
0  0.528893  0.608392  0.469695  0.060202  0.365066  0.979838  0.308809

        7         8         9   ...        11        12        13        14  \
0  0.04745  0.004294  0.045237  ... -0.039733  0.237768  2.459549  0.071788

         15        16        17        18        19        20
0  0.032139  0.293429  0.755856  3.277001  0.081932 -0.352729

[1 rows x 21 columns]


Logistic Regression Intercept:
0   -7.79723
dtype: float64


Mean squared error:
0.09165089877010407


Mean Squared Log Error:
0.044033950542408475


Median Absolute Error:
0.0


R2 Score:
-0.07640900468840894


Accuracy Score:
0.908349101229896


Kl Divergence:
inf


ROC AUC Score:
0.5601204037666321


Unique Values:
0    0.0
1    1.0
dtype: float64
Ridge Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Ridge Regression Intercept:
-0.14270589957679403


Mean squared error:
0.07244965790146864


Median Absolute Error:
0.08481782255129641


R2 Score:
0.14910311630054696


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Lasso Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


Lasso Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Mean Squared Log Error:
0.04152912296598731


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801277


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
ElasticNet Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


ElasticNet Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801278


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
Mini Batch SGD Classifier Coef:
0     3.249931
1     3.000867
2     1.006832
3    -0.060408
4     1.872501
5     3.528696
6     2.412563
7    -0.450228
8     0.218120
9    -0.166656
10   -0.742817
11    0.274712
12    0.548909
13    4.640031
14    0.580557
15    2.421096
16    2.978621
17    2.998615
18    7.549296
19   -0.986487
20   -2.382955
dtype: float64


Mini Batch SGD Classifier Intercept:
-11.36907251546996


Mean squared error:
0.3952223273415326


Median Absolute Error:
0.0


R2 Score:
-3.6417534111853715


Accuracy Score:
0.6047776726584674


Kl Divergence:
inf


ROC AUC Score:
0.7411006689071655


Unique Values:
0    0.0
1    1.0
dtype: float64

In [17]:
metrics_normalizer.main()

 Linear Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Linear Regression Intercept:
-0.14270589939952721


Mean squared error:
0.07244965790139588


Median Absolute Error:
0.0848178224741479


R2 Score:
0.14910311630140172


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Logistic Regression Coef:
         0         1         2         3         4         5         6   \
0  0.528893  0.608392  0.469695  0.060202  0.365066  0.979838  0.308809

        7         8         9   ...        11        12        13        14  \
0  0.04745  0.004294  0.045237  ... -0.039733  0.237768  2.459549  0.071788

         15        16        17        18        19        20
0  0.032139  0.293429  0.755856  3.277001  0.081932 -0.352729

[1 rows x 21 columns]


Logistic Regression Intercept:
0   -7.79723
dtype: float64


Mean squared error:
0.09165089877010407


Mean Squared Log Error:
0.044033950542408475


Median Absolute Error:
0.0


R2 Score:
-0.07640900468840894


Accuracy Score:
0.908349101229896


Kl Divergence:
inf


ROC AUC Score:
0.5601204037666321


Unique Values:
0    0.0
1    1.0
dtype: float64
Ridge Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Ridge Regression Intercept:
-0.14270589957679403


Mean squared error:
0.07244965790146864


Median Absolute Error:
0.08481782255129641


R2 Score:
0.14910311630054696


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Lasso Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


Lasso Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Mean Squared Log Error:
0.04152912296598731


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801277


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
ElasticNet Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


ElasticNet Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801278


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
Mini Batch SGD Classifier Coef:
0     3.249931
1     3.000867
2     1.006832
3    -0.060408
4     1.872501
5     3.528696
6     2.412563
7    -0.450228
8     0.218120
9    -0.166656
10   -0.742817
11    0.274712
12    0.548909
13    4.640031
14    0.580557
15    2.421096
16    2.978621
17    2.998615
18    7.549296
19   -0.986487
20   -2.382955
dtype: float64


Mini Batch SGD Classifier Intercept:
-11.36907251546996


Mean squared error:
0.3952223273415326


Median Absolute Error:
0.0


R2 Score:
-3.6417534111853715


Accuracy Score:
0.6047776726584674


Kl Divergence:
inf


ROC AUC Score:
0.7411006689071655


Unique Values:
0    0.0
1    1.0
dtype: float64

In [18]:
metrics_robust_scaler.main()

 Linear Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Linear Regression Intercept:
-0.14270589939952721


Mean squared error:
0.07244965790139588


Median Absolute Error:
0.0848178224741479


R2 Score:
0.14910311630140172


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Logistic Regression Coef:
         0         1         2         3         4         5         6   \
0  0.528893  0.608392  0.469695  0.060202  0.365066  0.979838  0.308809

        7         8         9   ...        11        12        13        14  \
0  0.04745  0.004294  0.045237  ... -0.039733  0.237768  2.459549  0.071788

         15        16        17        18        19        20
0  0.032139  0.293429  0.755856  3.277001  0.081932 -0.352729

[1 rows x 21 columns]


Logistic Regression Intercept:
0   -7.79723
dtype: float64


Mean squared error:
0.09165089877010407


Mean Squared Log Error:
0.044033950542408475


Median Absolute Error:
0.0


R2 Score:
-0.07640900468840894


Accuracy Score:
0.908349101229896


Kl Divergence:
inf


ROC AUC Score:
0.5601204037666321


Unique Values:
0    0.0
1    1.0
dtype: float64
Ridge Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Ridge Regression Intercept:
-0.14270589957679403


Mean squared error:
0.07244965790146864


Median Absolute Error:
0.08481782255129641


R2 Score:
0.14910311630054696


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Lasso Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


Lasso Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Mean Squared Log Error:
0.04152912296598731


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801277


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
ElasticNet Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


ElasticNet Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801278


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
Mini Batch SGD Classifier Coef:
0     3.249931
1     3.000867
2     1.006832
3    -0.060408
4     1.872501
5     3.528696
6     2.412563
7    -0.450228
8     0.218120
9    -0.166656
10   -0.742817
11    0.274712
12    0.548909
13    4.640031
14    0.580557
15    2.421096
16    2.978621
17    2.998615
18    7.549296
19   -0.986487
20   -2.382955
dtype: float64


Mini Batch SGD Classifier Intercept:
-11.36907251546996


Mean squared error:
0.3952223273415326


Median Absolute Error:
0.0


R2 Score:
-3.6417534111853715


Accuracy Score:
0.6047776726584674


Kl Divergence:
inf


ROC AUC Score:
0.7411006689071655


Unique Values:
0    0.0
1    1.0
dtype: float64

In [19]:
metrics_standard_scaler.main()

 Linear Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Linear Regression Intercept:
-0.14270589939952721


Mean squared error:
0.07244965790139588


Median Absolute Error:
0.0848178224741479


R2 Score:
0.14910311630140172


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Logistic Regression Coef:
         0         1         2         3         4         5         6   \
0  0.528893  0.608392  0.469695  0.060202  0.365066  0.979838  0.308809

        7         8         9   ...        11        12        13        14  \
0  0.04745  0.004294  0.045237  ... -0.039733  0.237768  2.459549  0.071788

         15        16        17        18        19        20
0  0.032139  0.293429  0.755856  3.277001  0.081932 -0.352729

[1 rows x 21 columns]


Logistic Regression Intercept:
0   -7.79723
dtype: float64


Mean squared error:
0.09165089877010407


Mean Squared Log Error:
0.044033950542408475


Median Absolute Error:
0.0


R2 Score:
-0.07640900468840894


Accuracy Score:
0.908349101229896


Kl Divergence:
inf


ROC AUC Score:
0.5601204037666321


Unique Values:
0    0.0
1    1.0
dtype: float64
Ridge Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Ridge Regression Intercept:
-0.14270589957679403


Mean squared error:
0.07244965790146864


Median Absolute Error:
0.08481782255129641


R2 Score:
0.14910311630054696


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Lasso Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


Lasso Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Mean Squared Log Error:
0.04152912296598731


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801277


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
ElasticNet Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


ElasticNet Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801278


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
Mini Batch SGD Classifier Coef:
0     3.249931
1     3.000867
2     1.006832
3    -0.060408
4     1.872501
5     3.528696
6     2.412563
7    -0.450228
8     0.218120
9    -0.166656
10   -0.742817
11    0.274712
12    0.548909
13    4.640031
14    0.580557
15    2.421096
16    2.978621
17    2.998615
18    7.549296
19   -0.986487
20   -2.382955
dtype: float64


Mini Batch SGD Classifier Intercept:
-11.36907251546996


Mean squared error:
0.3952223273415326


Median Absolute Error:
0.0


R2 Score:
-3.6417534111853715


Accuracy Score:
0.6047776726584674


Kl Divergence:
inf


ROC AUC Score:
0.7411006689071655


Unique Values:
0    0.0
1    1.0
dtype: float64

In [20]:
metrics_binarizer.main()

 Linear Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Linear Regression Intercept:
-0.14270589939952721


Mean squared error:
0.07244965790139588


Median Absolute Error:
0.0848178224741479


R2 Score:
0.14910311630140172


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Logistic Regression Coef:
         0         1         2         3         4         5         6   \
0  0.528893  0.608392  0.469695  0.060202  0.365066  0.979838  0.308809

        7         8         9   ...        11        12        13        14  \
0  0.04745  0.004294  0.045237  ... -0.039733  0.237768  2.459549  0.071788

         15        16        17        18        19        20
0  0.032139  0.293429  0.755856  3.277001  0.081932 -0.352729

[1 rows x 21 columns]


Logistic Regression Intercept:
0   -7.79723
dtype: float64


Mean squared error:
0.09165089877010407


Mean Squared Log Error:
0.044033950542408475


Median Absolute Error:
0.0


R2 Score:
-0.07640900468840894


Accuracy Score:
0.908349101229896


Kl Divergence:
inf


ROC AUC Score:
0.5601204037666321


Unique Values:
0    0.0
1    1.0
dtype: float64
Ridge Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Ridge Regression Intercept:
-0.14270589957679403


Mean squared error:
0.07244965790146864


Median Absolute Error:
0.08481782255129641


R2 Score:
0.14910311630054696


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Lasso Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


Lasso Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Mean Squared Log Error:
0.04152912296598731


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801277


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
ElasticNet Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


ElasticNet Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801278


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
Mini Batch SGD Classifier Coef:
0     3.249931
1     3.000867
2     1.006832
3    -0.060408
4     1.872501
5     3.528696
6     2.412563
7    -0.450228
8     0.218120
9    -0.166656
10   -0.742817
11    0.274712
12    0.548909
13    4.640031
14    0.580557
15    2.421096
16    2.978621
17    2.998615
18    7.549296
19   -0.986487
20   -2.382955
dtype: float64


Mini Batch SGD Classifier Intercept:
-11.36907251546996


Mean squared error:
0.3952223273415326


Median Absolute Error:
0.0


R2 Score:
-3.6417534111853715


Accuracy Score:
0.6047776726584674


Kl Divergence:
inf


ROC AUC Score:
0.7411006689071655


Unique Values:
0    0.0
1    1.0
dtype: float64

In [21]:
metrics_function_transformer.main()

 Linear Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Linear Regression Intercept:
-0.14270589939952721


Mean squared error:
0.07244965790139588


Median Absolute Error:
0.0848178224741479


R2 Score:
0.14910311630140172


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Logistic Regression Coef:
         0         1         2         3         4         5         6   \
0  0.528893  0.608392  0.469695  0.060202  0.365066  0.979838  0.308809

        7         8         9   ...        11        12        13        14  \
0  0.04745  0.004294  0.045237  ... -0.039733  0.237768  2.459549  0.071788

         15        16        17        18        19        20
0  0.032139  0.293429  0.755856  3.277001  0.081932 -0.352729

[1 rows x 21 columns]


Logistic Regression Intercept:
0   -7.79723
dtype: float64


Mean squared error:
0.09165089877010407


Mean Squared Log Error:
0.044033950542408475


Median Absolute Error:
0.0


R2 Score:
-0.07640900468840894


Accuracy Score:
0.908349101229896


Kl Divergence:
inf


ROC AUC Score:
0.5601204037666321


Unique Values:
0    0.0
1    1.0
dtype: float64
Ridge Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Ridge Regression Intercept:
-0.14270589957679403


Mean squared error:
0.07244965790146864


Median Absolute Error:
0.08481782255129641


R2 Score:
0.14910311630054696


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Lasso Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


Lasso Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Mean Squared Log Error:
0.04152912296598731


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801277


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
ElasticNet Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


ElasticNet Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801278


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
Mini Batch SGD Classifier Coef:
0     3.249931
1     3.000867
2     1.006832
3    -0.060408
4     1.872501
5     3.528696
6     2.412563
7    -0.450228
8     0.218120
9    -0.166656
10   -0.742817
11    0.274712
12    0.548909
13    4.640031
14    0.580557
15    2.421096
16    2.978621
17    2.998615
18    7.549296
19   -0.986487
20   -2.382955
dtype: float64


Mini Batch SGD Classifier Intercept:
-11.36907251546996


Mean squared error:
0.3952223273415326


Median Absolute Error:
0.0


R2 Score:
-3.6417534111853715


Accuracy Score:
0.6047776726584674


Kl Divergence:
inf


ROC AUC Score:
0.7411006689071655


Unique Values:
0    0.0
1    1.0
dtype: float64

In [22]:
metrics_KBinsDiscretizer.main()

 Linear Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Linear Regression Intercept:
-0.14270589939952721


Mean squared error:
0.07244965790139588


Median Absolute Error:
0.0848178224741479


R2 Score:
0.14910311630140172


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Logistic Regression Coef:
         0         1         2         3         4         5         6   \
0  0.528893  0.608392  0.469695  0.060202  0.365066  0.979838  0.308809

        7         8         9   ...        11        12        13        14  \
0  0.04745  0.004294  0.045237  ... -0.039733  0.237768  2.459549  0.071788

         15        16        17        18        19        20
0  0.032139  0.293429  0.755856  3.277001  0.081932 -0.352729

[1 rows x 21 columns]


Logistic Regression Intercept:
0   -7.79723
dtype: float64


Mean squared error:
0.09165089877010407


Mean Squared Log Error:
0.044033950542408475


Median Absolute Error:
0.0


R2 Score:
-0.07640900468840894


Accuracy Score:
0.908349101229896


Kl Divergence:
inf


ROC AUC Score:
0.5601204037666321


Unique Values:
0    0.0
1    1.0
dtype: float64
Ridge Regression Coef:
0     0.034075
1     0.038439
2     0.013089
3    -0.121782
4     0.023097
5     0.188192
6     0.049302
7     0.004049
8     0.003699
9     0.003634
10   -0.020996
11    0.006711
12    0.007132
13    0.164973
14   -0.005157
15    0.028615
16    0.049416
17    0.052903
18    0.141917
19    0.007175
20   -0.029569
dtype: float64


Ridge Regression Intercept:
-0.14270589957679403


Mean squared error:
0.07244965790146864


Median Absolute Error:
0.08481782255129641


R2 Score:
0.14910311630054696


Accuracy Score:
0.0


Kl Divergence:
nan


ROC AUC Score:
0.839693546295166


Unique Values:
0        0.037284
1        0.152095
2       -0.065624
3       -0.027555
4        0.200609
           ...
48601    0.063997
48602    0.146988
48603    0.018342
48604    0.086597
48605    0.194234
Length: 48606, dtype: float64
 Lasso Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


Lasso Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Mean Squared Log Error:
0.04152912296598731


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801277


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
ElasticNet Regression Coef:
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
dtype: float64


ElasticNet Regression Intercept:
0.09423781929990539


Mean squared error:
0.08514511843038028


Median Absolute Error:
0.09423781929990539


R2 Score:
-8.010136207659002e-07


Accuracy Score:
0.0


Kl Divergence:
11261.699877801278


ROC AUC Score:
0.5


Unique Values:
0    0.094238
dtype: float64
Mini Batch SGD Classifier Coef:
0     3.249931
1     3.000867
2     1.006832
3    -0.060408
4     1.872501
5     3.528696
6     2.412563
7    -0.450228
8     0.218120
9    -0.166656
10   -0.742817
11    0.274712
12    0.548909
13    4.640031
14    0.580557
15    2.421096
16    2.978621
17    2.998615
18    7.549296
19   -0.986487
20   -2.382955
dtype: float64


Mini Batch SGD Classifier Intercept:
-11.36907251546996


Mean squared error:
0.3952223273415326


Median Absolute Error:
0.0


R2 Score:
-3.6417534111853715


Accuracy Score:
0.6047776726584674


Kl Divergence:
inf


ROC AUC Score:
0.7411006689071655


Unique Values:
0    0.0
1    1.0
dtype: float64

In [23]:
ml.LogisticRegression()

In [24]:
logr_predict_global_1

         HeartDiseaseorAttack
0                         1.0
1                         1.0
2                         1.0
3                         1.0
4                         1.0
...                       ...
1999995                   1.0
1999996                   1.0
1999997                   1.0
1999998                   1.0
1999999                   1.0

[2000000 rows x 1 columns]